export const COUNTRY_TO_ISO: Record<string, string> = {
  Germany: "DE",
  France: "FR",
  UK: "GB",
  USA: "US",
  Mexico: "MX",
  Brazil: "BR",
  Spain: "ES",
  Italy: "IT",
  Sweden: "SE",
  Austria: "AT",
  Belgium: "BE",
  Switzerland: "CH",
  Canada: "CA",
  Denmark: "DK",
  Finland: "FI",
  Ireland: "IE",
  Norway: "NO",
  Poland: "PL",
  Portugal: "PT",
  Venezuela: "VE",
  Argentina: "AR",
};